[project]
name = "rikaiai-slack-selenium"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.0.1",
    "seleniumbase>=4.35.2",
]
